name: Update lunch data

on:
  schedule:
    - cron: '30 8 * * *'   # 08:30 UTC ~ 10:30 CEST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: List repo (diagnostics)
        run: |
          pwd
          ls -la
          echo "---- scripts ----"
          ls -la scripts || true

      - name: Install deps
        run: npm install

      - name: Generate data.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run generate

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data.json
          if ! git diff --cached --quiet; then
            git commit -m "chore: update lunch data $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
